# This is a basic workflow to help you get started with Actions

name: First workflow
on: workflow_dispatch
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello"
      - name: print goodbye
        run: echo "bye"
